# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisines',
            fields=[
                ('cuisine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cuisine_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipDetails',
            fields=[
                ('membership_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('membership_type', models.CharField(choices=[(b'B', b'BRONZE_MEMBERSHIP'), (b'S', b'SILVER_MEMBERSHIP'), (b'G', b'GOLD_MEMBERSHIP'), (b'P', b'PLATINUM_MEMBERSHIP')], max_length=1)),
                ('valid_for_months', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=70)),
                ('account_number', models.CharField(max_length=25)),
                ('IFSC_code', models.CharField(max_length=25)),
                ('bank_name', models.CharField(max_length=40)),
                ('created_datetime', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
            managers=[
                ('bank_details', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMembershipDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_valid_from', models.DateTimeField()),
                ('membership_valid_to', models.DateTimeField()),
                ('created_datetime', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantNotification',
            fields=[
                ('notification_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_message', models.TextField()),
                ('is_viewed', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('V', b'VEGETARIAN'), ('N', b'NON_VEGETARIAN'), ('M', b'MUTLI_CUISINE')], max_length=1)),
                ('mobile_number', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=150, null=True)),
                ('order_open_timing_from', models.CharField(max_length=5)),
                ('order_open_timing_to', models.CharField(max_length=5)),
                ('convenience_fee', models.IntegerField(blank=True, null=True)),
                ('commission_percentage', models.IntegerField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
            managers=[
                ('profile', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReviewRating',
            fields=[
                ('review_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_urls', models.TextField(blank=True)),
                ('rating', models.IntegerField()),
                ('review', models.CharField(blank=True, max_length=250)),
                ('created_datetime', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
