# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-24 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket_details', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantreviewrating',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_review_rating_restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantreviewrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_review_rating_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='cuisines',
            field=models.ManyToManyField(to='restaurant.Cuisines'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_profile_restaurant_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='restaurant_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_profile_restaurant_station', to='ticket_details.StationDetails'),
        ),
        migrations.AddField(
            model_name='restaurantnotification',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantmembershipdetails',
            name='membership_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_membership_details_membership_type', to='restaurant.MembershipDetails'),
        ),
        migrations.AddField(
            model_name='restaurantmembershipdetails',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_membership_details_restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantbankdetails',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurant_bank_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
