CUISINES = {'cuisines':
    [
        (1, 'South-Indian'),
        (2, 'North-Indian'),
        (3, 'Italian'),
        (4, 'Chinese'),
        (5, 'Mexican'),
        (6, 'Andhra Cuisine'),
        (7, 'Assamese Cuisine'),
        (8, 'Bengali Cuisine'),
        (9, 'Bihari Cuisine'),
        (10, 'Goan Cuisine'),
        (11, 'Gujarathi Cuisine'),
        (12, 'Jharkhandi Cuisine'),
        (13, 'Karnataka Cuisine'),
        (14, 'Kashmiri Cuisine'),
        (15, 'Kerala Cuisine'),
        (16, 'Maharastrain Cuisine'),
        (17, 'Nagaland Cuisine'),
        (18, 'Odia Cuisine'),
        (19, 'Rajasthani Cuisine'),
        (20, 'Tamil Cuisine'),
        (21, 'Telangana Cuisine'),
        (22, 'Tripuri Cuisine'),
        (23, 'Uttar Pradeshi Cuisine'),
        (24, 'Bihari Cuisine'),
        (25, 'Arunachal Pradesh Cuisine'),
        (26, 'Chattisgarh Cuisine'),
        (27, 'Manipur Cuisine'),
        (28, 'Meghalaya Cuisine'),
        (29, 'Jharkhand Cuisine'),
        (30, 'Maithili Cuisine'),
        (31, 'Sikkimese Cuisine')
    ]
}