from BAAS.config import BRONZE_MEMBERSHIP_CODE, SILVER_MEMBERSHIP_CODE, GOLD_MEMBERSHIP_CODE, PLATINUM_MEMBERSHIP_CODE, \
    BRONZE_MEMBERSHIP_MONTHS_VALIDITY, SILVER_MEMBERSHIP_MONTHS_VALIDITY, GOLD_MEMBERSHIP_MONTHS_VALIDITY, PLATINUM_MEMBERSHIP_MONTHS_VALIDITY, \
    BRONZE_MEMBERSHIP_PRICING, SILVER_MEMBERSHIP_PRICING, GOLD_MEMBERSHIP_PRICING, PLATINUM_MEMBERSHIP_PRICING, PRICE_KEY, \
    VALIDITY_KEY, TYPE_KEY

MEMBERSHIP_DETAILS = {0:{TYPE_KEY: BRONZE_MEMBERSHIP_CODE,
                         PRICE_KEY: BRONZE_MEMBERSHIP_PRICING,
                         VALIDITY_KEY: BRONZE_MEMBERSHIP_MONTHS_VALIDITY},

                      1: {TYPE_KEY: SILVER_MEMBERSHIP_CODE,
                          PRICE_KEY: SILVER_MEMBERSHIP_PRICING,
                          VALIDITY_KEY: SILVER_MEMBERSHIP_MONTHS_VALIDITY},

                      2: {TYPE_KEY: GOLD_MEMBERSHIP_CODE,
                          PRICE_KEY: GOLD_MEMBERSHIP_PRICING,
                          VALIDITY_KEY: GOLD_MEMBERSHIP_MONTHS_VALIDITY},

                      3: {TYPE_KEY: PLATINUM_MEMBERSHIP_CODE,
                          PRICE_KEY: PLATINUM_MEMBERSHIP_PRICING,
                          VALIDITY_KEY: PLATINUM_MEMBERSHIP_MONTHS_VALIDITY},
                      }