# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_no', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('created_datetime', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StationDetails',
            fields=[
                ('station_code', models.CharField(db_index=True, max_length=7, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=15)),
                ('created_datetime', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('pnr_no', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('date_of_journey', models.DateField()),
                ('is_cancelled', models.BooleanField()),
                ('is_chart_prepared', models.BooleanField()),
                ('created_datetime', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('boarding_station', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boarding_station_id', to='ticket_details.StationDetails')),
                ('destination_station', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination_station_id', to='ticket_details.StationDetails')),
                ('train_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='train_details.TrainDetails')),
            ],
        ),
    ]
