# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-24 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket_details', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seatdetails',
            name='pnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pnr', to='ticket_details.TicketDetails'),
        ),
    ]
